var num1 = 7;
var num2 = 3;
var num3 = 4;
console.log('num1 = ' + num1);
console.log('num2 = ' + num2);
console.log('Sum:');
console.log(num1 + num2);
console.log('Substraction:');
console.log(num1 - num2);
console.log('Multiplication:');
console.log(num1 * num2);
console.log('Division:');
console.log(num1 / num2);
console.log('Modulo:');
console.log(num1 % num2);
console.log('num3 = ' + num3);
console.log('Post-incrementor:');
console.log(num3++);
console.log(num3);
console.log('Post-incrementor:');
console.log(++num3);
console.log(num3);
console.log('Post-decrementor:');
console.log(num3--);
console.log(num3);
console.log('Pre-decrementor:');
console.log(--num3);
console.log(num3);
// -------
var num4 = "num1 = " + num1;
//# sourceMappingURL=08_arithmetic_operations.js.map